Document: blitzinfod
Title: Debian blitzinfod Manual
Author: <insert document author here>
Abstract: This manual describes what blitzinfod is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/blitzinfod/blitzinfod.sgml.gz

Format: postscript
Files: /usr/share/doc/blitzinfod/blitzinfod.ps.gz

Format: text
Files: /usr/share/doc/blitzinfod/blitzinfod.text.gz

Format: HTML
Index: /usr/share/doc/blitzinfod/html/index.html
Files: /usr/share/doc/blitzinfod/html/*.html
