# blitzd.toml
# This is the configuration file for blitzd.
# The file format is TOML (https://github.com/toml-lang/toml).

# Do not make any changes to this file because they would be overwritten on
# the next update or removed on uninstall. Instead create a file in
# ~/.blitzd.toml and override the values there.

# alias:
alias = "some-alias"

# admin settings
[admin]
  # password: used for HTTP Basic Auth on Web Interface
  #password = "$2y$05$nNUGiiHDDric6W/Zml05Ku0Ij04mf62NTd/JRWQya8uxLpoGR3yJS"

  # username: used for HTTP Basic Auth on Web Interface
  #username = "admin"

# client settings
[client]
  # cacert:
  #cacert = "~/.blitzd/blitzd_ca.crt"

  # tlscert:
  #tlscert = ""

  # tlskey:
  #tlskey = ""

# server settings
[server]
  # cacert:
  #cacert = ""

  # tlscert:
  #tlscert = ""

  # tlskey:
  #tlskey = ""

  [server.http]
    # enabled: run this server - or don't
    #enabled = true

    # localhost_only: whether to listen on localhost only or on all interfaces
    #localhost_only = true

    # port:
    #port = 39080

  [server.https]
    # enabled: run this server - or don't
    #enabled = true

    # localhost_only: whether to listen on localhost only or on all interfaces
    #localhost_only = true

    # port:
    #port = 39443

  [server.rpc]
    # enabled: run this server - or don't
    #enabled = true

    # localhost_only: whether to listen on localhost only or on all interfaces
    #localhost_only = true

    # port:
    #port = 39735

[module]

  [module.system]
	  # enabled: run this module or don't
	  #enabled = true
	  
	  # mount1: mount number 1
	  #mount1 = "/"
	  
	  # mount2: mount number 2
	  #mount2 = "/mnt/hdd/"
	  

  [module.lnd]
	  # enabled: run this module or don't
	  #enabled = false
	  
	  # rpcaddress: Host and Port of LND RPC (check lnd.conf: "restlisten")
	  #rpcaddress = "localhost:10009"

	  # tlscert:
	  #tlscert = "/home/bitcoin/.lnd/tls.cert"

  [module.network]
	  # enabled: run this module or don't
	  #enabled = false
	  
	  # nic: Name of Network Interface Card to use (usually "eth0" or "wifi0")
	  #nic = "eth0"
	  

  [module.raspiblitz]
	  # enabled: run this module or don't
	  #enabled = false
	  
	  # path: path to raspiblitz config file
	  #path" = "/mnt/hdd/raspiblitz.conf"
