// Copyright (c) 2013-2017 The btcsuite developers
// Copyright (c) 2015-2016 The Decred developers
// Copyright (C) 2015-2017 The Lightning Network Developers

package util

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"io/ioutil"
	"log"
	"math/big"
	"net"
	"os"
	"time"
)

const (
	// Make certificate valid for 14 months.
	autogenCertValidity = 14 /*months*/ * 30 /*days*/ * 24 * time.Hour
)

var (
	// End of ASN.1 time.
	endOfTime = time.Date(2049, 12, 31, 23, 59, 59, 0, time.UTC)

	// Max serial number.
	serialNumberLimit = new(big.Int).Lsh(big.NewInt(1), 128)
)

// genCertPair generates a key/cert pair to the paths provided. The
// auto-generated certificates should *not* be used in production for public
// access as they're self-signed and don't necessarily contain all of the
// desired hostnames for the service. For production/public use, consider a
// real PKI.
//
// This function is adapted from https://github.com/lightningnetwork/lnd/,
// https://github.com/btcsuite/btcd and https://github.com/btcsuite/btcutil
func GenCertPair(certFile, keyFile string) error {
	//rpcsLog.Infof("Generating TLS certificates...")
	fmt.Printf("Generating TLS certificates...")

	org := "lnd autogenerated cert"
	now := time.Now()
	validUntil := now.Add(autogenCertValidity)

	// Check that the certificate validity isn't past the ASN.1 end of time.
	if validUntil.After(endOfTime) {
		validUntil = endOfTime
	}

	// Generate a serial number that's below the serialNumberLimit.
	serialNumber, err := rand.Int(rand.Reader, serialNumberLimit)
	if err != nil {
		return fmt.Errorf("failed to generate serial number: %s", err)
	}

	// Collect the host's IP addresses, including loopback, in a slice.
	ipAddresses := []net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")}

	// addIP appends an IP address only if it isn't already in the slice.
	addIP := func(ipAddr net.IP) {
		for _, ip := range ipAddresses {
			if bytes.Equal(ip, ipAddr) {
				return
			}
		}
		ipAddresses = append(ipAddresses, ipAddr)
	}

	// Add all the interface IPs that aren't already in the slice.
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return err
	}
	for _, a := range addrs {
		ipAddr, _, err := net.ParseCIDR(a.String())
		if err == nil {
			addIP(ipAddr)
		}
	}

	// Add extra IPs to the slice.
	//for _, ip := range cfg.TLSExtraIPs {
	//	ipAddr := net.ParseIP(ip)
	//	if ipAddr != nil {
	//		addIP(ipAddr)
	//	}
	//}

	// Collect the host's names into a slice.
	host, err := os.Hostname()
	if err != nil {
		return err
	}
	dnsNames := []string{host}
	if host != "localhost" {
		dnsNames = append(dnsNames, "localhost")
	}
	//dnsNames = append(dnsNames, cfg.TLSExtraDomains...)

	// Also add fake hostnames for unix sockets, otherwise hostname
	// verification will fail in the client.
	dnsNames = append(dnsNames, "unix", "unixpacket")

	// Generate a private key for the certificate.
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return err
	}

	// Construct the certificate template.
	template := x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			Organization: []string{org},
			CommonName:   host,
		},
		NotBefore: now.Add(-time.Hour * 24),
		NotAfter:  validUntil,

		KeyUsage: x509.KeyUsageKeyEncipherment |
			x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		IsCA:                  true, // so can sign self.
		BasicConstraintsValid: true,

		DNSNames:    dnsNames,
		IPAddresses: ipAddresses,
	}

	derBytes, err := x509.CreateCertificate(rand.Reader, &template,
		&template, &priv.PublicKey, priv)
	if err != nil {
		return fmt.Errorf("failed to create certificate: %v", err)
	}

	certBuf := &bytes.Buffer{}
	err = pem.Encode(certBuf, &pem.Block{Type: "CERTIFICATE",
		Bytes: derBytes})
	if err != nil {
		return fmt.Errorf("failed to encode certificate: %v", err)
	}

	keybytes, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		return fmt.Errorf("unable to encode privkey: %v", err)
	}
	keyBuf := &bytes.Buffer{}
	err = pem.Encode(keyBuf, &pem.Block{Type: "EC PRIVATE KEY",
		Bytes: keybytes})
	if err != nil {
		return fmt.Errorf("failed to encode private key: %v", err)
	}

	// Write cert and key files.
	if err = ioutil.WriteFile(certFile, certBuf.Bytes(), 0644); err != nil {
		return err
	}
	if err = ioutil.WriteFile(keyFile, keyBuf.Bytes(), 0600); err != nil {
		_ = os.Remove(certFile)
		return err
	}

	fmt.Printf("Done generating TLS certificates")
	return nil
}

func GenRootCaSignedClientServerCert(storeRootCaKey bool) error {

	rootCaCertPath := "ca.crt"
	rootCaKeyPath := "ca.key"

	clientCertPath := "client.crt"
	clientKeyPath := "client.key"

	serverCertPath := "server.crt"
	serverKeyPath := "server.key"

	// get Root CA and store and save as PEM.
	rootCaCert, rootCaPriv := GenRootCa()
	rootCaCertPem := pem.EncodeToMemory(pemBlockForCert(rootCaCert))
	_ = exportCert(rootCaCert, rootCaCertPath)
	rootCaPrivPem := pem.EncodeToMemory(pemBlockForKey(rootCaPriv))
	// Only store key if requested.
	if storeRootCaKey {
		_ = exportKey(rootCaPriv, rootCaKeyPath)
	}

	// create signed certificate for "client" and "server" with RootCA from memory
	signedClientCert, signedClientCertPriv := GenCaSignedCert(rootCaCertPem, rootCaPrivPem, "Blitzd Client")
	_ = exportCert(signedClientCert, clientCertPath)
	_ = exportKey(signedClientCertPriv, clientKeyPath)

	signedServerCert, signedServerCertPriv := GenCaSignedCert(rootCaCertPem, rootCaPrivPem, "Blitzd")
	_ = exportCert(signedServerCert, serverCertPath)
	_ = exportKey(signedServerCertPriv, serverKeyPath)

	return nil
}

func publicKey(priv interface{}) interface{} {
	switch k := priv.(type) {
	case *rsa.PrivateKey:
		return &k.PublicKey
	case *ecdsa.PrivateKey:
		return &k.PublicKey
	default:
		return nil
	}
}

func pemBlockForCert(cert []byte) *pem.Block {
	return &pem.Block{Type: "CERTIFICATE", Bytes: cert}
}

func pemBlockForKey(priv *ecdsa.PrivateKey) *pem.Block {
	b, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "Unable to marshal ECDSA private key: %v", err)
		os.Exit(2)
	}
	return &pem.Block{Type: "EC PRIVATE KEY", Bytes: b}
}

func exportCert(cert []byte, path string) error {

	// Public key
	certOut, err := os.Create(path)
	if err != nil {
		log.Printf("failed to open "+path+" for writing: %s", err)
		return err
	}

	_ = pem.Encode(certOut, &pem.Block{Type: "CERTIFICATE", Bytes: cert})
	_ = certOut.Close()
	log.Print("written " + path + "\n")

	return nil
}

func exportKey(key *ecdsa.PrivateKey, path string) error {

	// Private key
	keyOut, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		log.Printf("failed to open "+path+" for writing: %s", err)
		return err
	}

	_ = pem.Encode(keyOut, pemBlockForKey(key))
	_ = keyOut.Close()
	log.Print("written " + path + "\n")

	return nil

}

func genPrivKey(ecdsaCurve string) *ecdsa.PrivateKey {

	var priv *ecdsa.PrivateKey
	var err error
	switch ecdsaCurve {
	case "":
		priv, err = ecdsa.GenerateKey(elliptic.P224(), rand.Reader)
	case "P256":
		priv, err = ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	case "P384":
		priv, err = ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
	case "P521":
		priv, err = ecdsa.GenerateKey(elliptic.P521(), rand.Reader)
	default:
		_, _ = fmt.Fprintf(os.Stderr, "Unrecognized elliptic curve: %q", ecdsaCurve)
		os.Exit(1)
	}
	if err != nil {
		log.Printf("failed to generate private key: %s", err)
		panic(err)
	}

	return priv
}

// ToDo delete?!
func Check(certPath string, keyPath string) error {
	if _, err := os.Stat(certPath); os.IsNotExist(err) {
		return err
	} else if _, err := os.Stat(keyPath); os.IsNotExist(err) {
		return err
	}
	return nil
}

func GenRootCa() ([]byte, *ecdsa.PrivateKey) {
	ca := &x509.Certificate{
		SerialNumber: big.NewInt(1653),
		Subject: pkix.Name{
			Organization: []string{"Blitzd Ephemeral CA"},
			Country:      []string{"DE"},
		},
		NotBefore:             time.Now(),
		NotAfter:              time.Now().AddDate(0, 6, 0),
		IsCA:                  true,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth, x509.ExtKeyUsageServerAuth},
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign,
		BasicConstraintsValid: true,
		MaxPathLen:            0,
		MaxPathLenZero:        true,
	}

	priv := genPrivKey("P256")

	signedRootCaCert, err := x509.CreateCertificate(rand.Reader, ca, ca, publicKey(priv), priv)
	if err != nil {
		log.Printf("Failed to create Root CA certificate: %s", err)
		panic(err)
	}

	return signedRootCaCert, priv

}

func GenCaSignedCert(certPEMBlock, keyPEMBlock []byte, commonName string) ([]byte, *ecdsa.PrivateKey) {

	// Load CA
	catls, err := tls.X509KeyPair(certPEMBlock, keyPEMBlock)
	if err != nil {
		panic(err)
	}
	ca, err := x509.ParseCertificate(catls.Certificate[0])
	if err != nil {
		panic(err)
	}

	// Prepare certificate
	cert := &x509.Certificate{
		SerialNumber: big.NewInt(1658),
		Subject: pkix.Name{
			Organization: []string{"Blitzd Leaf Certificates"},
			Country:      []string{"DE"},
			CommonName:   commonName,
		},
		NotBefore:    time.Now(),
		NotAfter:     time.Now().AddDate(10, 0, 0),
		SubjectKeyId: []byte{1, 2, 3, 4, 6},
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth, x509.ExtKeyUsageServerAuth},
		KeyUsage:     x509.KeyUsageDigitalSignature,
	}

	priv := genPrivKey("P256")

	signedCert, err := x509.CreateCertificate(rand.Reader, cert, ca, publicKey(priv), catls.PrivateKey)
	if err != nil {
		panic(err)
	}

	return signedCert, priv
}
